SystemOrganization addCategory: #'Wizard-Battle-Arena'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Animation'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Descriptors'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Event-Handlers'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Front-End'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Game-Core'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Widgets-Arena'!
SystemOrganization addCategory: 'Wizard-Battle-Arena-Widgets-Screen'!
